# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint and Sort

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  LINTING_BUDGET: 3  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 and isort
      run: |
        touch settings.py
        chmod +x sort_and_lint.sh
        ./sort_and_lint.sh > results.txt
        cat results.txt >> $GITHUB_STEP_SUMMARY 
        error_count=`wc -l < results.txt`
        if [[ $error_count -gt $LINTING_BUDGET ]]; then exit 1; else exit 0; fi
